### ISSUE TITLE
Please check for graphviz in the bootstrap script

### ISSUE THREAD

**Issue by dbjergaard** [mcviz/mcviz#97]
By default the bootstrap script doesn't check the graphviz installed. This leads to a successful installation that is broken when you run it without graphviz installed.

**Comment by pwaller** [comment]
Pull requests welcome, if you fancy taking a crack at it :)

If you (or anyone else does) fancy doing it, please claim it first!

**Comment by brookst** [comment]
Hi, I'm just adding this now.

**Comment by dbjergaard** [comment]
Thanks for addressing this so fast. Also, this program is really great I wish I had known about it sooner.

**Comment by brookst** [comment]
This seems to work in my tests.

Thanks for pointing this out. We probably should try to generate some publicity for MCViz but I'm not sure if anyone has time at the moment.

**Comment by pwaller** [comment]
:+1:
